/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BLOBS_H_RPCGEN
#define _BLOBS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct pcsamp_parameters {
	u_int sampling_rate;
};
typedef struct pcsamp_parameters pcsamp_parameters;

struct pcsamp_data {
	uint64_t interval;
	struct {
		u_int pc_len;
		uint64_t *pc_val;
	} pc;
	struct {
		u_int count_len;
		uint8_t *count_val;
	} count;
};
typedef struct pcsamp_data pcsamp_data;

struct pcsamp_start_sampling_args {
	u_int sampling_rate;
	int experiment;
	int collector;
};
typedef struct pcsamp_start_sampling_args pcsamp_start_sampling_args;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_pcsamp_parameters (XDR *, pcsamp_parameters*);
extern  bool_t xdr_pcsamp_data (XDR *, pcsamp_data*);
extern  bool_t xdr_pcsamp_start_sampling_args (XDR *, pcsamp_start_sampling_args*);

#else /* K&R C */
extern bool_t xdr_pcsamp_parameters ();
extern bool_t xdr_pcsamp_data ();
extern bool_t xdr_pcsamp_start_sampling_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BLOBS_H_RPCGEN */
