/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BLOBS_H_RPCGEN
#define _BLOBS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct hwctime_parameters {
	uint64_t sampling_rate;
	char hwctime_event[128];
};
typedef struct hwctime_parameters hwctime_parameters;

struct hwctime_data {
	uint64_t interval;
	struct {
		u_int bt_len;
		uint64_t *bt_val;
	} bt;
	struct {
		u_int count_len;
		uint8_t *count_val;
	} count;
};
typedef struct hwctime_data hwctime_data;

struct hwctime_start_sampling_args {
	uint64_t sampling_rate;
	char hwctime_event[128];
	int experiment;
	int collector;
};
typedef struct hwctime_start_sampling_args hwctime_start_sampling_args;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_hwctime_parameters (XDR *, hwctime_parameters*);
extern  bool_t xdr_hwctime_data (XDR *, hwctime_data*);
extern  bool_t xdr_hwctime_start_sampling_args (XDR *, hwctime_start_sampling_args*);

#else /* K&R C */
extern bool_t xdr_hwctime_parameters ();
extern bool_t xdr_hwctime_data ();
extern bool_t xdr_hwctime_start_sampling_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BLOBS_H_RPCGEN */
