/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BLOBS_H_RPCGEN
#define _BLOBS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct io_parameters {
	uint8_t traced[1024];
};
typedef struct io_parameters io_parameters;

struct io_event {
	uint64_t start_time;
	uint64_t stop_time;
	uint16_t stacktrace;
};
typedef struct io_event io_event;

struct io_data {
	struct {
		u_int stacktraces_len;
		uint64_t *stacktraces_val;
	} stacktraces;
	struct {
		u_int events_len;
		io_event *events_val;
	} events;
};
typedef struct io_data io_data;

struct io_start_tracing_args {
	int experiment;
	int collector;
};
typedef struct io_start_tracing_args io_start_tracing_args;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_io_parameters (XDR *, io_parameters*);
extern  bool_t xdr_io_event (XDR *, io_event*);
extern  bool_t xdr_io_data (XDR *, io_data*);
extern  bool_t xdr_io_start_tracing_args (XDR *, io_start_tracing_args*);

#else /* K&R C */
extern bool_t xdr_io_parameters ();
extern bool_t xdr_io_event ();
extern bool_t xdr_io_data ();
extern bool_t xdr_io_start_tracing_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BLOBS_H_RPCGEN */
