/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "blobs.h"

bool_t
xdr_io_parameters (XDR *xdrs, io_parameters *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->traced, 1024,
		sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_io_event (XDR *xdrs, io_event *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, &objp->start_time))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->stop_time))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->stacktrace))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_io_data (XDR *xdrs, io_data *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->stacktraces.stacktraces_val, (u_int *) &objp->stacktraces.stacktraces_len, ~0,
		sizeof (uint64_t), (xdrproc_t) xdr_uint64_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->events.events_val, (u_int *) &objp->events.events_len, ~0,
		sizeof (io_event), (xdrproc_t) xdr_io_event))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_io_start_tracing_args (XDR *xdrs, io_start_tracing_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->experiment))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->collector))
		 return FALSE;
	return TRUE;
}
