/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "blobs.h"

bool_t
xdr_fpe_type (XDR *xdrs, fpe_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fpe_parameters (XDR *xdrs, fpe_parameters *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->traced, 8,
		sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fpe_event (XDR *xdrs, fpe_event *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, &objp->start_time))
		 return FALSE;
	 if (!xdr_fpe_type (xdrs, &objp->fpexception))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->stacktrace))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fpe_data (XDR *xdrs, fpe_data *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->stacktraces.stacktraces_val, (u_int *) &objp->stacktraces.stacktraces_len, ~0,
		sizeof (uint64_t), (xdrproc_t) xdr_uint64_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->events.events_val, (u_int *) &objp->events.events_len, ~0,
		sizeof (fpe_event), (xdrproc_t) xdr_fpe_event))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fpe_start_tracing_args (XDR *xdrs, fpe_start_tracing_args *objp)
{
	register int32_t *buf;

	 if (!xdr_fpe_type (xdrs, &objp->fpe_traced))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->experiment))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->collector))
		 return FALSE;
	return TRUE;
}
