/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "offline.h"

bool_t
xdr_openss_objects (XDR *xdrs, openss_objects *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->objname, ~0))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->addr_begin))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->addr_end))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->time_begin))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->time_end))
		 return FALSE;
	 if (!xdr_uint8_t (xdrs, &objp->is_open))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_offline_data (XDR *xdrs, offline_data *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->objs.objs_val, (u_int *) &objp->objs.objs_len, ~0,
		sizeof (openss_objects), (xdrproc_t) xdr_openss_objects))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_openss_expinfo (XDR *xdrs, openss_expinfo *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->collector, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->exename, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->traced, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->event, ~0))
		 return FALSE;
	 if (!xdr_int32_t (xdrs, &objp->rank))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->omptid))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->rate))
		 return FALSE;
	return TRUE;
}
