/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPENSS_DATAHEADER_H_RPCGEN
#define _OPENSS_DATAHEADER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct OpenSS_DataHeader {
	int experiment;
	int collector;
	char host[256];
	int64_t pid;
	int64_t posix_tid;
	uint64_t time_begin;
	uint64_t time_end;
	uint64_t addr_begin;
	uint64_t addr_end;
};
typedef struct OpenSS_DataHeader OpenSS_DataHeader;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_OpenSS_DataHeader (XDR *, OpenSS_DataHeader*);

#else /* K&R C */
extern bool_t xdr_OpenSS_DataHeader ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPENSS_DATAHEADER_H_RPCGEN */
