/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "blobs.h"

bool_t
xdr_hwcsamp_parameters (XDR *xdrs, hwcsamp_parameters *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_u_int (xdrs, &objp->sampling_rate))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hwcsamp_event, 512,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_evcounts (XDR *xdrs, evcounts objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 6,
		sizeof (uint64_t), (xdrproc_t) xdr_uint64_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hwcsamp_event (XDR *xdrs, hwcsamp_event *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->hwccounts, 6,
		sizeof (uint64_t), (xdrproc_t) xdr_uint64_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hwcsamp_data (XDR *xdrs, hwcsamp_data *objp)
{
	register int32_t *buf;

	 if (!xdr_uint64_t (xdrs, &objp->interval))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->pc.pc_val, (u_int *) &objp->pc.pc_len, ~0,
		sizeof (uint64_t), (xdrproc_t) xdr_uint64_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->count.count_val, (u_int *) &objp->count.count_len, ~0,
		sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->events.events_val, (u_int *) &objp->events.events_len, ~0,
		sizeof (hwcsamp_event), (xdrproc_t) xdr_hwcsamp_event))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->clock_mhz))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_hwcsamp_start_sampling_args (XDR *xdrs, hwcsamp_start_sampling_args *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_u_int (xdrs, &objp->sampling_rate))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hwcsamp_event, 512,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->experiment))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->collector))
		 return FALSE;
	return TRUE;
}
