/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BLOBS_H_RPCGEN
#define _BLOBS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct usertime_parameters {
	u_int sampling_rate;
};
typedef struct usertime_parameters usertime_parameters;

struct usertime_data {
	uint64_t interval;
	struct {
		u_int bt_len;
		uint64_t *bt_val;
	} bt;
	struct {
		u_int count_len;
		uint8_t *count_val;
	} count;
};
typedef struct usertime_data usertime_data;

struct usertime_start_sampling_args {
	u_int sampling_rate;
	int experiment;
	int collector;
};
typedef struct usertime_start_sampling_args usertime_start_sampling_args;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_usertime_parameters (XDR *, usertime_parameters*);
extern  bool_t xdr_usertime_data (XDR *, usertime_data*);
extern  bool_t xdr_usertime_start_sampling_args (XDR *, usertime_start_sampling_args*);

#else /* K&R C */
extern bool_t xdr_usertime_parameters ();
extern bool_t xdr_usertime_data ();
extern bool_t xdr_usertime_start_sampling_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BLOBS_H_RPCGEN */
